//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechBack_Cus
    {
        public int Id { get; set; }
        public string F_name { get; set; }
        public string F_content { get; set; }
        public string F_email { get; set; }
        public Nullable<int> F_Status { get; set; }
        public string F_image { get; set; }
    }
}
