//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_company
    {
        public int Id { get; set; }
        public string Name_CPN { get; set; }
        public Nullable<int> Phone_hot { get; set; }
        public Nullable<int> Bank_number { get; set; }
        public string Email_true { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Email_CPN { get; set; }
        public string Youtube { get; set; }
        public string Google { get; set; }
        public string Viber { get; set; }
        public string Slogan { get; set; }
        public string Addred { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> Register { get; set; }
        public string Notification_TB { get; set; }
        public string Advertisement_QC { get; set; }
        public string Best_Company { get; set; }
    }
}
