//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Introduction
    {
        public int Id { get; set; }
        public string Intro_name { get; set; }
        public string Intro_desc { get; set; }
        public string Intro_image { get; set; }
        public string Intro_link { get; set; }
        public string Intro_title { get; set; }
        public Nullable<bool> Intro_status { get; set; }
    }
}
