//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_DT
    {
        public int Id { get; set; }
        public string Name_partner { get; set; }
        public string image_partner { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
