//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_user
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_uer { get; set; }
        public Nullable<int> Id_brand { get; set; }
        public string Image { get; set; }
        public string Author { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<int> View_client { get; set; }
        public Nullable<System.DateTime> Time_up { get; set; }
        public Nullable<bool> Type_post { get; set; }
        public Nullable<bool> Common { get; set; }
    }
}
