//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_system
    {
        public int Id { get; set; }
        public string Ten_DuAn { get; set; }
        public string Ten_KySu { get; set; }
        public Nullable<decimal> Tongtien_DuAn { get; set; }
        public string Diachi_DuAn { get; set; }
        public Nullable<System.DateTime> Thoigiankhoicong { get; set; }
        public Nullable<System.DateTime> Thoigianhoanthanh { get; set; }
        public string Hinhanhchitiet { get; set; }
        public string Hinhanhmota { get; set; }
        public string Motangan { get; set; }
        public string ChiTietDuAn { get; set; }
        public string Ghi_chu { get; set; }
        public Nullable<int> TheLoai_DuAn { get; set; }
    }
}
