//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Id { get; set; }
        public string Services_name { get; set; }
        public string Services_title { get; set; }
        public string Services_link { get; set; }
        public string Services_image { get; set; }
        public string Services_desc { get; set; }
        public Nullable<bool> Services_status { get; set; }
        public Nullable<bool> Services_maketting { get; set; }
        public string Services_note { get; set; }
    }
}
