//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftWare_Case
    {
        public int Id { get; set; }
        public string Sw_title { get; set; }
        public string Sw_name { get; set; }
        public string Sw_image { get; set; }
        public string Sw_link { get; set; }
        public Nullable<bool> Sw_Status { get; set; }
        public string Sw_note { get; set; }
        public string Sw_desc { get; set; }
        public string Sw_author { get; set; }
    }
}
