//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question_client
    {
        public int Id_question { get; set; }
        public string Conten_question { get; set; }
        public string Email_question { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Time_question { get; set; }
    }
}
