//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uers_Admin
    {
        public int Id_user { get; set; }
        public string Email_user { get; set; }
        public string Password_user { get; set; }
        public string Image_user { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
