//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_congty.Modal.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uers
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string Image_cus { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<int> Run_status { get; set; }
        public Nullable<int> phone { get; set; }
        public string question { get; set; }
        public string reply { get; set; }
        public string addred { get; set; }
        public Nullable<int> type_uer { get; set; }
        public Nullable<int> public_private { get; set; }
        public string folow { get; set; }
    }
}
